### PR TITLE
Add HQMTool folder

### PR DESCRIPTION
**Pull request by DavidAKopriva**
Add the code, documentation and examples to the repo for the HQMTool interactive front end.

### CODE REVIEW

**Comment by sloede** [comment]
@DavidAKopriva There has been a small change to how this branch can be used from now on: You also need to explicitly use GLMakie.jl, since it is not included as a hard dependency anymore. We use the same procedure for Trixi to make it easier for those who do not have GL installed or who only need the mesh generation without plotting.

That is, to load HOHQMesh from this branch with plotting enabled, you need to execute
```julia
julia> using Revise, GLMakie, HOHQMesh
```

Please let me know if you have any questions or if something doesn't work as expected.

**Comment by DavidAKopriva** [comment]
Just starting to see how the new version runs. I get the following message on the first run:

┌ Warning: Package HOHQMesh does not have Printf in its dependencies:
│ - If you have HOHQMesh checked out for development and have
│   added Printf as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with HOHQMesh
└ Loading Printf into HOHQMesh from project dependency, future warnings for HOHQMesh are suppressed.

**Comment by DavidAKopriva** [comment]
And 

        proj.plt = Figure(resolution = (1500, 1500))

gives the error 

 UndefVarError: Figure not defined

even though I did run

 using Revise, GLMakie, HOHQMesh

**Comment by DavidAKopriva** [comment]
Works if using GLMakie is returned to the vizProject file. But mesh doesn't plot anymore in runDemo. probably a directory issues.

**Comment by sloede** [comment]
> Just starting to see how the new version runs. I get the following message on the first run:
> 
> ┌ Warning: Package HOHQMesh does not have Printf in its dependencies:
> │ - If you have HOHQMesh checked out for development and have
> │ added Printf as a dependency but haven't updated your primary
> │ environment's manifest file, try `Pkg.resolve()`.
> │ - Otherwise you may need to report an issue with HOHQMesh
> └ Loading Printf into HOHQMesh from project dependency, future warnings for HOHQMesh are suppressed.

Please delete the `Manifest.toml` file in your branch directory and try again. The error should disappear. If not, please let me know.

**Comment by sloede** [comment]
> And
> 
> ```
>     proj.plt = Figure(resolution = (1500, 1500))
> ```
> 
> gives the error
> 
> UndefVarError: Figure not defined
> 
> even though I did run
> 
> using Revise, GLMakie, HOHQMesh



> Works if using GLMakie is returned to the vizProject file. But mesh doesn't plot anymore in runDemo. probably a directory issues.

Hm, I cannot reproduce either error. Have you started Julia from within the `HOHQMesh.jl/` directory with
```shell
julia --project=.
```
and then executed
```julia
julia> using Revise, HOHQMesh, GLMakie

julia> HOHQMesh.runDemo()
```
?

This yields for me the following plot:
image

**Comment by sloede** [comment]
FWIW, there _should_ be no need to re-add `using GLMakie` to any of the files, since we are already `using Makie` via the line
https://github.com/trixi-framework/HOHQMesh.jl/blob/e3b5b5c16f59d804792c9e79ab871f0dbdba6cce/src/HOHQMesh.jl#L15
in `src/HOHQMesh.jl`.

**Comment by DavidAKopriva** [comment]
Yes, the plot is missing the mesh that plots after the "any key" is hit. I'm using VScode, so I'm not sure what the directory is, but I will try pwd to see.

**Comment by DavidAKopriva** [comment]
Not sure why all the gymnastics. 

julia> --project=.
ERROR: syntax: invalid operator "--"
Stacktrace:
 [1] top-level scope
   @ none:1

**Comment by sloede** [comment]
> Yes, the plot is missing the mesh that plots after the "any key" is hit. I'm using VScode, so I'm not sure what the directory is, but I will try pwd to see.

I can confirm that the mesh is missing for me, too. Dunno why though. It seems weird that everything works except the mesh visualization. Maybe because it's now contained in a module? Needs to be investigated...



> Not sure why all the gymnastics.
> 
> julia> --project=.
> ERROR: syntax: invalid operator "--"
> Stacktrace:
> [1] top-level scope
> @ none:1

The `julia --project=.` refers to how you start Julia from the command line. It's not something you execute in the REPL. VS Code should allow something similar, but I've never used it - maybe @jlchan or @ranocha can help?

**Comment by ranocha** [comment]
> The `julia --project=.` refers to how you start Julia from the command line. It's not something you execute in the REPL. VS Code should allow something similar, but I've never used it - maybe @jlchan or @ranocha can help?

I don't use the terminal of VSCode, sorry

**Comment by jlchan** [comment]
If I understand correctly, the `--project=.` flag just specified the  environment to activate on Julia startup. For VSCode, one should be able to achieve the same effect by making a new window and having VSCode open the folder containing the environment to activate.

**Comment by andrewwinters5000** [comment]
We need to write some tests to cover all the new HQMTool routines. Everything works but we should not let coverage drop from 100% to 2%

**Comment by DavidAKopriva** [comment]
I presume Julia has a built in testing API like python and Java do? I'll have a look. If so, I hope it is easy to set up.

**Comment by andrewwinters5000** [comment]
figure for the docs
iceCreamCone

**Comment by andrewwinters5000** [comment]
Development of the HQMTool has moved entirely #15

**Pull request closed without merging**
