### PR TITLE
Removed deprecated keyword from plotting

### PR DESCRIPTION
**Pull request by andrewwinters5000**
The keyword `resolution` has been deprecated in Makie and we now use the new suggested keyword `size` for all the `Figure` creation. Once this is merged I will release a new version.

### CODE REVIEW

**Comment by ranocha** [comment]
Thanks. Do we need to update

https://github.com/trixi-framework/HOHQMesh.jl/blob/c55aa26f8745ef3147ac6bf872822d899113551c/test/Project.toml#L8

as well?

**Comment by andrewwinters5000** [comment]
> Thanks. Do we need to update
> 
> https://github.com/trixi-framework/HOHQMesh.jl/blob/c55aa26f8745ef3147ac6bf872822d899113551c/test/Project.toml#L8
> 
> as well?

Good catch, yes we should update this. I will check the Makie page to see for which version this deprecation happened.

**Comment by andrewwinters5000** [comment]
So the deprecation happened with the release of Makie 0.20. I have yet to work out if this places a limit on the front end for GLMakie (for users) or CairoMakie (for testing).

**Review by ranocha — APPROVED** [review]
Thanks! We should finally use package extensions managing the compatibility correctly. But that should be done in another PR.

**Comment by andrewwinters5000** [comment]
> Thanks! We should finally use package extensions managing the compatibility correctly. But that should be done in another PR.

Okay, this is related to creating a `Downgrade.yml`, right?

**Comment by ranocha** [comment]
It's related to it but independent of it. We use a proper package extension in Trixi.jl for the Makie plotting stuff

**Comment by andrewwinters5000** [comment]
Jaha, so basically something along the lines of this PR from Trixi? https://github.com/trixi-framework/Trixi.jl/pull/1494/files#diff-6058d487915aa254cfe1a5f8da6315b8c1fef4da04df38b0089a599803e28e5a

**Comment by ranocha** [comment]
Yes :+1:

**Pull request merged**
